version: '3'
services:
  client:
    image: node:18
    container_name: client
    working_dir: /app
    ports:
      - '3000:3000'
    depends_on:
      - server
      - dataBase
    command: npm run start
    volumes:
      - ./client:/app
  server:
    image: node:18
    container_name: server
    ports:
      - '9001:9001'
    depends_on:
      - dataBase
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm run start:dev
  dataBase:
    image: mysql:latest
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dataBase
    ports:
      - 3306:3306
    volumes: 
      - ./data/database-data:/var/lib/postgresql/data/